#!/bin/bash

#
# CTF_PASSWORD (authentication session)
#

password="${PASSWORD}"

if test $(id -u) -ne 0; then
    echo "You must run this script as root." 1>&2
    exit 1
fi

create_ctf_user()
{
    # Create user if it does not exist.
    if ! id ctf > /dev/null 2>&1; then
        useradd -m -d /home/ctf -s /bin/bash ctf
    fi
    # TODO: Check if home is /home/ctf; if not, fail.
    # Disable password for account (can't login with password).
    passwd -l ctf
    # Prevent password changing.
    passwd -n 9999 ctf
    # Prevent ctf user from writing to home folder.
    chown -R root:ctf /home/ctf
    chmod 750 /home/ctf
}

# Create ctf user if it does not exist and update password.
create_ctf_user
echo "ctf:$password" | chpasswd
passwd -u ctf

# Flag must be unaccessible to ctf user.
cp flag /home/ctf/flag
chmod 400 /home/ctf/flag

# Set capabilities allowing all users to use /usr/bin/rev.
setcap cap_dac_read_search+ep /usr/bin/sha512sum
chmod o+x /sbin/getcap

# Announce removal of files.
echo
echo "IMPORTANT: Remove all deployed files (flag, setup)."
echo
