---
title: "Authentication"
subtitle: "Software Security and Privacy --- Lecture 02 --- Full"
format:
  revealjs:
    theme: default
    slide-number: c/t
    slide-level: 2
    width: 1280
    height: 720
    embed-resources: true
    link-external-newwindow: true
  beamer:
    aspectratio: 169
    slide-level: 2
---

# Motivation

## Password Statistics

> **TODO (figure):** password statistics overview, from slides.tex (img/password-stats.png).

Source: <https://spacelift.io/blog/password-statistics>

## Cause of Lost Passwords

> **TODO (figure):** causes of lost passwords, from slides.tex (img/cause-of-lost-passwords.png).

Source: <https://www.huntress.com/blog/password-statistics>

## Password Cracking Time

> **TODO (figure):** time needed to crack passwords by length and charset, from slides.tex (img/password-cracking-time.png).

Source: <https://www.hivesystems.com/blog/are-your-passwords-in-the-green>

## Access Control Terms

* authentication
* authorization
* access control

## Papers

* [On the Accuracy of Password Strength Meters](https://dl.acm.org/doi/10.1145/3243734.3243769) (ACM CCS 2018)
* [Accessorize to a Crime: Real and Stealthy Attacks on State-of-the-Art Face Recognition](https://dl.acm.org/doi/10.1145/2976749.2978392) (ACM CCS 2016)

# Authentication

## Model

* actor / subject / agent
* credentials database (role, permissions, access control list)
* resource / object
* reference monitor

## Credentials

* who you are
* what you have
* what you know

## Credential Types

* biometric
* hardware tokens
* software tokens
* secret (password)

# Credentials

## Biometrics

* fingerprint
* face
* iris
* voice
* keystroke dynamics

## Hardware Tokens

* access card
* hardware keys
* one-time password (OTP)

## Software Tokens

* certificate
* Kerberos ticket
* cookie

# Password-based Access

## Passwords

* string of printable characters (ASCII)
* protect access
* stored in a password database and requested at each login / authentication
* most common method of authentication

## Password Cracking Context (1)

> **TODO (figure):** xkcd 936, password strength, from slides.tex (img/password-strength.png).

Source: <http://xkcd.com/936/>

## Password Cracking Context (2)

> **TODO (figure):** password complexity and its effect on cracking effort, from slides.tex (img/password-complexity.png).

Source: <http://hitachi-id.com/password-manager/docs/password-management-best-practices.pdf>

## Passwords vs. Passphrases

* a password is a word and a passphrase is a set of words
* passphrases usually have spaces
* passphrases are recommended due to their increased length and being easier to remember

## Attacker

* online attack
  * "live" attack
  * run client / application, feed passwords and try to match
* offline attack

## Scenario 1: Plaintext

* attacker
  * gain access to database
  * profit!
* defender
  * database access control
  * one-way function

# Securing Password-based Access

## Cryptographic Hash Functions

* deterministic
* uniformity
* infeasible to reverse
* highly dynamic
* usually very fast

## Hash Security Properties

* pre-image resistance
* second pre-image resistance
* collision resistance

## Hash Algorithms

* broken or weak: SHA1, MD2, MD4, MD5
* acceptable: SHA2
* recommended: bcrypt, SHA3

## Scenario 2: Hashed Password

* attacker
  * rainbow tables
  * profit!
* defender
  * salt

## Rainbow Tables

* database of hashes
* space vs. time

## Rainbow Tables (2)

> **TODO (figure):** rainbow table structure: chains of hash and reduction steps, from slides.tex (img/rainbow-table.png).

Source: <http://en.wikipedia.org/wiki/Rainbow_table>

## Salt

* additional input
* concatenated with the password
* one per password

## Scenario 3: Salted Hashes

* attacker
  * dictionary / hybrid attack
  * brute-force attack
  * side-channel attacks
  * profit ?!?
* defender
  * policies
  * defensive programming

## Dictionary Attacks

* use a dictionary / word list
* go through the word list, compute the hash and compare it to the password hash
* simple form of attack
* relies on people using simple passwords

## Password Dictionaries / Word Lists

* <http://wiki.skullsecurity.org/Passwords>
* <https://crackstation.net/buy-crackstation-wordlist-password-cracking-dictionary.htm>
* <http://security.stackexchange.com/questions/9567/modern-high-quality-password-dictionary>

## Hybrid Attack

* use a dictionary
* apply mutations for each word
  * combine dictionary words
  * change i to 1, s to 5, e to 3
  * change cases
  * add 123 at the end of the word
  * add ! at the end of the word
* hash and check with the password hash

## Policy

* complexity
  * password length
  * charset
* password expiration
* password reuse

## Policy Issues

* password security paradox
  * easy to remember
  * hard to guess
* user behavior
* solution: password managers

## Side-Channel Attacks

* timing information
* performance / power consumption
* electromagnetic leak
* acoustic information
* social engineering
* rubber-hose technique

## Rubber-hose Technique

> **TODO (figure):** xkcd 538, security (the wrench), from slides.tex (img/security-wrench.png).

Source: <http://xkcd.com/538/>

# Summary

## Recommendations

* do not use unsafe hashing algorithms
* passphrase > complex password
* use / allow password managers
* use 2FA / 3FA
* secure side channels

## Common Tools

* [John The Ripper](http://www.openwall.com/john/)
* [RainbowCrack](http://project-rainbowcrack.com/)
* [HashCat](https://hashcat.net/hashcat/)

## Keywords

::::: {.columns}
::: {.column width="50%"}

* credentials
* password
* passphrase
* hash functions
* rainbow tables
* salt
* dictionary attack
* side-channel attack
* policies

:::
::: {.column width="50%"}

* social engineering
* shoulder surfing
* one-time password
* password complexity
* password manager
* 2/3 factor authentication
* SHA256, SHA512
* SHA3
* rubber-hose technique

:::
:::::

## Nice to Read

* [Targeted Online Password Guessing: An Underestimated Threat](https://dl.acm.org/doi/10.1145/2976749.2978339) (ACM CCS 2016)
* [On the Accuracy of Password Strength Meters](https://dl.acm.org/doi/10.1145/3243734.3243769) (ACM CCS 2018)
* [Accessorize to a Crime: Real and Stealthy Attacks on State-of-the-Art Face Recognition](https://dl.acm.org/doi/10.1145/2976749.2978392) (ACM CCS 2016)
* [An Empirical Study of Mnemonic Sentence-based Password Generation Strategies](https://dl.acm.org/doi/10.1145/2976749.2978346) (ACM CCS 2016)

## Nice to Read (2)

* [Password Cracking Techniques](http://books.expect-us.net/dl/Password_Cracking_Techniques.pdf)
* [Breaking the iris scanner locking Samsung's Galaxy S8 is laughably easy](https://arstechnica.com/information-technology/2017/05/breaking-the-iris-scanner-locking-samsungs-galaxy-s8-is-laughably-easy/)
* [Galaxy S8 face recognition already defeated with a simple picture](https://arstechnica.com/gadgets/2017/03/video-shows-galaxy-s8-face-recognition-can-be-defeated-with-a-picture/)
* [Bypassing TouchID was "no challenge at all," hacker tells Ars](https://arstechnica.com/information-technology/2013/09/touchid-hack-was-no-challenge-at-all-hacker-tells-ars/)
* [Behavioral Profiling: The password you can't change](https://paul.reviews/behavioral-profiling-the-password-you-cant-change/)
