#!/bin/bash

password="CTF_PASSWORD"
remote=ctf@CTF_HOST
remote_port=22

# Two ways to extract flag through SSH. That's how cool and smart we are.
sshpass -p "$password" ssh -o StrictHostKeyChecking=no "$remote" -p "$remote_port" "cd /home/ctf; /usr/bin/rev flag" | rev
expect -c 'spawn ssh '"$remote"' -p '"$remote_port"' "cd /home/ctf; /usr/bin/rev flag"; expect "assword:"; send "'"$password"'\r"; interact' | rev
