#!/bin/bash

cat ../passwords.hash | python3 dictionary_breaking.py | python3 hybrid_breaking.py | python3 extended_breaking.py | python3 salt_breaking.py | python3 extended_salt_breaking.py | python3 brute_force_breaking.py
